import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";

import Section from "@/components/ui/Section";
import Stack from "@/components/ui/Stack";
import { inter } from "@/utils/fonts";
import Footer from "@/components/Footer";
import cn from "@/utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <Stack vertical className="gap-16  h-full ">
          {/* <Navbar /> */}
          {children}
        </Stack>
      </body>
    </html>
  );
}
